name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-compiler:
          - 5.2.0
        skip_tests:
          - false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gcc MacOS
        run: |
          brew install gcc
          brew link gcc
        if: matrix.os == 'macos-latest'

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
        if: matrix.os != 'windows-latest'

      - name: Use OCaml ${{ matrix.ocaml-compiler }} on Windows
        uses: kit-ty-kate/setup-ocaml@win52
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true
          opam-repositories: git+https://github.com/dra27/opam-repository.git#windows-initial
        if: matrix.os == 'windows-latest'

      - name: Install dependencies
        run: |
          opam install . --with-test --deps-only

      - name: Build project on MacOS
        run: |
          opam exec -- dune build
        env:
          CC: gcc-14
          CXX: gcc-14
        if: matrix.os == 'macos-latest'

      - name: Build project
        run: |
          opam exec -- dune build
        if: matrix.os != 'macos-latest'

      - name: Run tests
        run: |
          opam exec -- dune runtest

