name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 5.2.0
        skip_tests:
          - false
        include:
          - os: windows-latest
            ocaml-compiler: 4.14.1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: |
          opam install . --with-test --deps-only

      - name: Build project
        run: |
          opam exec -- dune build
        if: matrix.os != 'macos-latest'

      - name: Build project on macOS
        run: |
          opam exec -- dune build --profile macosx
        if: matrix.os == 'macos-latest'

      - name: Run tests
        run: |
          opam exec -- dune runtest

